### ISSUE TITLE
Ошибка при включенных потоках в параллельном бекенде

### ISSUE THREAD

**Issue by byaka** [byaka/flaskJSONRPCServer#27]
Если включен gevent, при параллельном выполнении запроса в лог вываливается ошибка
```python
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/threading.py", line 783, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 857, in __bootstrap_inner
    with _active_limbo_lock:
AttributeError: __exit__
<Greenlet at 0x7fc547fab9b0: <bound method Thread.__bootstrap of <Thread(Thread-1, started 140485292898736)>>> failed with AttributeError
```
которая **не влияет на работоспособность**. Причину ошибки выявить не удалось

**Comment by byaka** [comment]
Детальное тестирование показало, что проблема намного хуже. В дочернем процессе попытка использовать патченные через gevent **threading** и **sleep** вызывает "умирание".

**Comment by byaka** [comment]
Пока проблема не решена, в дочернем процессе принудительно включен _importAll(forceDelete=True). Если же allowThreads==True, диспетчеры вызываются в настоящих процессах

**Comment by byaka** [comment]
Проблема частично решена. Негативные эффекты устранены, осталась только надоедливая ошибка в логах.
Поскольку проблема теперь не влияет на работоспособность, параметр **allowThread** включен по умолчанию.
Также это позволяет наконец то реализовать функционал, описанный в #48 без использования нативных потоков (а значит без проблем с race-condition)

**Comment by byaka** [comment]
Оказывается данная проблема проявляется не только с gevent, но и с обычными потоками. удалось найти такую информацию https://goo.gl/TFyzYM
похоже это старый баг в питоне, проявляющийся при определенных условиях и в самом деле не влияющий на работоспособность.

**Comment by byaka** [comment]
Возможно этот баг пофиксится после закрытия #82

**Comment by byaka** [comment]
Проблема не проявлялась уже 3 месяца, возможно всеже удалось ее решить.
Нужно еще раз прогнать все тесты.

**Comment by byaka** [comment]
Провел тесты, проблема действительно не возникает. Тестировал на python 2.7 и python 2.6.

Похоже проблема действительно решилась после закрытия #82.

**Comment by VitaliySyrotyuk** [comment]
https://byaka.github.io/flaskJSONRPCServer-docs/pages/module_flaskJSONRPCServer__execBackend__parallelWithSocket.html

Есть русские комменты
